[package]
name = "dns-tunneling"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "server"
path = "src/server.rs"

[[bin]]
name = "client"
path = "src/client.rs"


[dependencies]
base64 = "0.22.1"
nix = "0.30.1"
trust-dns-proto = "0.23.2"
mio = { version = "0.8", features = ["os-poll", "net", "os-ext"] }
